telegram:
  # Telegram token to send duels schedule and outcome
  token: put_telegram_toke_here
  groups:
    # Groups where you want to send information to
    - id: -1001702841817
      thread_id: 32
  control_group:
    # Tournament manager group id.
    # Used by bin/telegram_control to notify tournament
    # managers of errors
    id: -12345678
twitter:
  # Twitter credentails to tweet duels schedule and outcome
  api_key: twitter_api_key
  api_key_secret: twitter_api_secret
  access_token: twitter_api_access_token
  access_token_secret: twitter_access_secret
schedule:
  results: '07:00'
  schedule: '07:01'

bga:
  user: someuser
  password: 123456_or_maybe_a_good_one
  interval: 2 # Seconds before doing repeated requests
  urls:
    home: https://en.boardgamearena.com/account
    login: https://en.boardgamearena.com/account/account/login.html
    csrf: https://boardgamearena.com/gamestats?player=84486751&game_id=1
    outcome: https://boardgamearena.com/gamestats/gamestats/getGames.html?player={0}&opponent_id={1}&game_id=1&finished=1&start_date={2}&end_date={3}&updateStats=0
    outcome_link: https://boardgamearena.com/gamestats?player={0}&opponent_id={1}&game_id=1&finished=1&start_date={2}&end_date={3}
    player_link: https://boardgamearena.com/player?id={0}

header:
  results: '📡 Últimos resultados 📡'
  # schedule: '<a href="https://docs.google.com/spreadsheets/u/3/d/e/2PACX-1vQUfs_HUfPlUPAAHfFy42cURAj4NiEnd_TT-5e-TsMLA93FIckyxDk7uOGbNaRB-JB2VtBbQH94P_C3/pubhtml#">⏰ Duelos para hoy ⏰</a>'
  schedule: '⏰ Duelos para hoy ⏰'

groups:
  Élite:
    order: 1
    players: https://docs.google.com/spreadsheets/d/e/2PACX-1vTe3Tz79ZRI1PuCV8vAicUGambbx0TgLXVTzhtwl240E3mOvS_uf4rgVJ6VkJ2RX3i3q1qQrVNwPrnP/pub?gid=363689283&single=true&output=csv
    results: https://docs.google.com/spreadsheets/d/e/2PACX-1vQNcqIT8VksaP1XwBofMIzTrina9m0DmAxhWSINyUSK7owu0MO8etxpTqQS7roY-2j_T6GjhurPtAwX/pub?gid=0&single=true&output=csv
    schedule: https://docs.google.com/spreadsheets/d/e/2PACX-1vQmuYMhCUy2PwRdsjtZ8fmRoUTrK-6z-Rgc44WD1XiHzgDefIvT6MHQFZN6GPGzNjERW-y905bEkRN5/pub?gid=0&single=true&output=csv
  Azul:
    order: 2
    players: https://docs.google.com/spreadsheets/d/e/2PACX-1vTe3Tz79ZRI1PuCV8vAicUGambbx0TgLXVTzhtwl240E3mOvS_uf4rgVJ6VkJ2RX3i3q1qQrVNwPrnP/pub?gid=1464030688&single=true&output=csv
    results: https://docs.google.com/spreadsheets/d/e/2PACX-1vQNcqIT8VksaP1XwBofMIzTrina9m0DmAxhWSINyUSK7owu0MO8etxpTqQS7roY-2j_T6GjhurPtAwX/pub?gid=1115036289&single=true&output=csv
    schedule: https://docs.google.com/spreadsheets/d/e/2PACX-1vQmuYMhCUy2PwRdsjtZ8fmRoUTrK-6z-Rgc44WD1XiHzgDefIvT6MHQFZN6GPGzNjERW-y905bEkRN5/pub?gid=1518156767&single=true&output=csv
  Rojo:
    order: 3
    players: https://docs.google.com/spreadsheets/d/e/2PACX-1vTe3Tz79ZRI1PuCV8vAicUGambbx0TgLXVTzhtwl240E3mOvS_uf4rgVJ6VkJ2RX3i3q1qQrVNwPrnP/pub?gid=561683622&single=true&output=csv
    results: https://docs.google.com/spreadsheets/d/e/2PACX-1vQNcqIT8VksaP1XwBofMIzTrina9m0DmAxhWSINyUSK7owu0MO8etxpTqQS7roY-2j_T6GjhurPtAwX/pub?gid=1233394230&single=true&output=csv
    schedule: https://docs.google.com/spreadsheets/d/e/2PACX-1vQmuYMhCUy2PwRdsjtZ8fmRoUTrK-6z-Rgc44WD1XiHzgDefIvT6MHQFZN6GPGzNjERW-y905bEkRN5/pub?gid=1608355815&single=true&output=csv
  Verde:
    order: 4
    players: https://docs.google.com/spreadsheets/d/e/2PACX-1vTe3Tz79ZRI1PuCV8vAicUGambbx0TgLXVTzhtwl240E3mOvS_uf4rgVJ6VkJ2RX3i3q1qQrVNwPrnP/pub?gid=481307165&single=true&output=csv
    results: https://docs.google.com/spreadsheets/d/e/2PACX-1vQNcqIT8VksaP1XwBofMIzTrina9m0DmAxhWSINyUSK7owu0MO8etxpTqQS7roY-2j_T6GjhurPtAwX/pub?gid=153836702&single=true&output=csv
    schedule: https://docs.google.com/spreadsheets/d/e/2PACX-1vQmuYMhCUy2PwRdsjtZ8fmRoUTrK-6z-Rgc44WD1XiHzgDefIvT6MHQFZN6GPGzNjERW-y905bEkRN5/pub?gid=1095718215&single=true&output=csv
