telegram:
  # Telegram token to send duels schedule and outcome
  token: put_telegram_toke_here
  groups:
    # Groups where you want to send information to
    - id: -1001702841817
      thread_id: 32
  control_group:
    # Tournament manager group id.
    # Used by bin/telegram_control to notify tournament
    # managers of errors
    id: -12345678
  header:
    results: '<b>📡 Últimos resultados 📡</b>'
    schedule: '<b><a href="https://docs.google.com/spreadsheets/d/e/2PACX-1vTQgViRubR7qSeJubBOYR335aVaLBdD9jpxkqqIb-KRC1u4iUt7rtCs4j_zY_zC8ycLKO95u98TFgVC/pubhtml">⏰ Duelos para hoy ⏰</a></b>'
twitter:
  # Twitter credentails to tweet duels schedule and outcome
  api_key: twitter_api_key
  api_key_secret: twitter_api_secret
  access_token: twitter_api_access_token
  access_token_secret: twitter_access_secret
  header:
    results: '📡 Últimos resultados #LigaCSonline 📡'
    schedule: '⏰ Duelos para hoy #LigaCSonline ⏰'

google:
  calendar_id: 80fd10e42324bd2c99210479c53bda4928d76d8f5f235b31eab7053762bcdd2c@group.calendar.google.com

schedule:
  results: '07:00'
  schedule: '07:01'

bga:
  user: someuser
  password: 123456_or_maybe_a_good_one
  interval: 5 # Seconds before doing repeated requests
  urls:
    home: https://en.boardgamearena.com/account
    login: https://en.boardgamearena.com/account/account/login.html
    csrf: https://boardgamearena.com/gamestats?player=84486751&game_id=1
    outcome: https://boardgamearena.com/gamestats/gamestats/getGames.html?player={0}&opponent_id={1}&game_id=1&finished=1&start_date={2}&end_date={3}&updateStats=0
    outcome_link: https://boardgamearena.com/gamestats?player={0}&opponent_id={1}&game_id=1&finished=1&start_date={2}&end_date={3}
    player_link: https://boardgamearena.com/player?id={0}


league:
  - season: 2
    groups:
      Élite:
        order: 1
        gcalendar_color: 3
        players: https://docs.google.com/spreadsheets/d/e/2PACX-1vTe3Tz79ZRI1PuCV8vAicUGambbx0TgLXVTzhtwl240E3mOvS_uf4rgVJ6VkJ2RX3i3q1qQrVNwPrnP/pub?gid=363689283&single=true&output=csv
        results: https://docs.google.com/spreadsheets/d/e/2PACX-1vQNcqIT8VksaP1XwBofMIzTrina9m0DmAxhWSINyUSK7owu0MO8etxpTqQS7roY-2j_T6GjhurPtAwX/pub?gid=0&single=true&output=csv
        schedule: https://docs.google.com/spreadsheets/d/e/2PACX-1vQmuYMhCUy2PwRdsjtZ8fmRoUTrK-6z-Rgc44WD1XiHzgDefIvT6MHQFZN6GPGzNjERW-y905bEkRN5/pub?gid=0&single=true&output=csv
      Azul:
        order: 2
        gcalendar_color: 9
        players: https://docs.google.com/spreadsheets/d/e/2PACX-1vTe3Tz79ZRI1PuCV8vAicUGambbx0TgLXVTzhtwl240E3mOvS_uf4rgVJ6VkJ2RX3i3q1qQrVNwPrnP/pub?gid=1464030688&single=true&output=csv
        results: https://docs.google.com/spreadsheets/d/e/2PACX-1vQNcqIT8VksaP1XwBofMIzTrina9m0DmAxhWSINyUSK7owu0MO8etxpTqQS7roY-2j_T6GjhurPtAwX/pub?gid=1115036289&single=true&output=csv
        schedule: https://docs.google.com/spreadsheets/d/e/2PACX-1vQmuYMhCUy2PwRdsjtZ8fmRoUTrK-6z-Rgc44WD1XiHzgDefIvT6MHQFZN6GPGzNjERW-y905bEkRN5/pub?gid=1518156767&single=true&output=csv
      Rojo:
        order: 3
        gcalendar_color: 11
        players: https://docs.google.com/spreadsheets/d/e/2PACX-1vTe3Tz79ZRI1PuCV8vAicUGambbx0TgLXVTzhtwl240E3mOvS_uf4rgVJ6VkJ2RX3i3q1qQrVNwPrnP/pub?gid=561683622&single=true&output=csv
        results: https://docs.google.com/spreadsheets/d/e/2PACX-1vQNcqIT8VksaP1XwBofMIzTrina9m0DmAxhWSINyUSK7owu0MO8etxpTqQS7roY-2j_T6GjhurPtAwX/pub?gid=1233394230&single=true&output=csv
        schedule: https://docs.google.com/spreadsheets/d/e/2PACX-1vQmuYMhCUy2PwRdsjtZ8fmRoUTrK-6z-Rgc44WD1XiHzgDefIvT6MHQFZN6GPGzNjERW-y905bEkRN5/pub?gid=1608355815&single=true&output=csv
      Verde:
        order: 4
        gcalendar_color: 2
        players: https://docs.google.com/spreadsheets/d/e/2PACX-1vTe3Tz79ZRI1PuCV8vAicUGambbx0TgLXVTzhtwl240E3mOvS_uf4rgVJ6VkJ2RX3i3q1qQrVNwPrnP/pub?gid=481307165&single=true&output=csv
        results: https://docs.google.com/spreadsheets/d/e/2PACX-1vQNcqIT8VksaP1XwBofMIzTrina9m0DmAxhWSINyUSK7owu0MO8etxpTqQS7roY-2j_T6GjhurPtAwX/pub?gid=153836702&single=true&output=csv
        schedule: https://docs.google.com/spreadsheets/d/e/2PACX-1vQmuYMhCUy2PwRdsjtZ8fmRoUTrK-6z-Rgc44WD1XiHzgDefIvT6MHQFZN6GPGzNjERW-y905bEkRN5/pub?gid=1095718215&single=true&output=csv
  - season: 3
    groups:
      Élite:
        order: 1
        gcalendar_color: 3
        players: https://docs.google.com/spreadsheets/d/e/2PACX-1vSTCu8KzgqQEvK9r5ChHn42owKyzbYKf4Dpasg1Gzra8JTd7LvqnqJ4tSO_sEdtOT3fpayT1Qtem0dI/pub?output=csv&gid=363689283
        results: https://docs.google.com/spreadsheets/d/e/2PACX-1vSI-AcWpDBAgk_Q-u4q884fliIQvruzu-ar45b0UNCCbI43GJV9yzWJjggrmJmGVo0PtX2KdvvgAZGC/pub?output=csv&gid=0
        schedule: https://docs.google.com/spreadsheets/d/e/2PACX-1vQsrWnQbutIEgz7Zz9zcR4DYBJacHnWg5jch07FyBl3L3b8oWyNaIPhZ6uYB6PyooKJD1X3VHMJJr_H/pub?gid=0&single=true&output=csv
      Segunda:
        order: 2
        gcalendar_color: 9
        players: https://docs.google.com/spreadsheets/d/e/2PACX-1vSTCu8KzgqQEvK9r5ChHn42owKyzbYKf4Dpasg1Gzra8JTd7LvqnqJ4tSO_sEdtOT3fpayT1Qtem0dI/pub?output=csv&gid=561683622
        results: https://docs.google.com/spreadsheets/d/e/2PACX-1vSI-AcWpDBAgk_Q-u4q884fliIQvruzu-ar45b0UNCCbI43GJV9yzWJjggrmJmGVo0PtX2KdvvgAZGC/pub?output=csv&gid=1078056963
        schedule: https://docs.google.com/spreadsheets/d/e/2PACX-1vQsrWnQbutIEgz7Zz9zcR4DYBJacHnWg5jch07FyBl3L3b8oWyNaIPhZ6uYB6PyooKJD1X3VHMJJr_H/pub?gid=384769640&single=true&output=csv
      Naranja:
        order: 6
        gcalendar_color: 3
        players: https://docs.google.com/spreadsheets/d/e/2PACX-1vSTCu8KzgqQEvK9r5ChHn42owKyzbYKf4Dpasg1Gzra8JTd7LvqnqJ4tSO_sEdtOT3fpayT1Qtem0dI/pub?output=csv&gid=481307165
        results: https://docs.google.com/spreadsheets/d/e/2PACX-1vSI-AcWpDBAgk_Q-u4q884fliIQvruzu-ar45b0UNCCbI43GJV9yzWJjggrmJmGVo0PtX2KdvvgAZGC/pub?output=csv&gid=1290077699
        schedule: https://docs.google.com/spreadsheets/d/e/2PACX-1vQsrWnQbutIEgz7Zz9zcR4DYBJacHnWg5jch07FyBl3L3b8oWyNaIPhZ6uYB6PyooKJD1X3VHMJJr_H/pub?gid=828628157&single=true&output=csv 
      Rosa:
        order: 4
        gcalendar_color: 4
        players: https://docs.google.com/spreadsheets/d/e/2PACX-1vSTCu8KzgqQEvK9r5ChHn42owKyzbYKf4Dpasg1Gzra8JTd7LvqnqJ4tSO_sEdtOT3fpayT1Qtem0dI/pub?output=csv&gid=1464030688
        results: https://docs.google.com/spreadsheets/d/e/2PACX-1vSI-AcWpDBAgk_Q-u4q884fliIQvruzu-ar45b0UNCCbI43GJV9yzWJjggrmJmGVo0PtX2KdvvgAZGC/pub?output=csv&gid=413133258
        schedule: https://docs.google.com/spreadsheets/d/e/2PACX-1vQsrWnQbutIEgz7Zz9zcR4DYBJacHnWg5jch07FyBl3L3b8oWyNaIPhZ6uYB6PyooKJD1X3VHMJJr_H/pub?gid=1174688863&single=true&output=csv
  - season: 4
    groups:
      Élite:
        order: 1
        gcalendar_color: 3
        players: https://docs.google.com/spreadsheets/d/e/2PACX-1vQZkFhb83WaxFiiu3B4iOBhkEd9Cau8KzLswH1waFn6yI8aForqBqn3a4OKpq7nqrENxgByYvKAp5LE/pub?output=csv&gid=363689283
        results: https://docs.google.com/spreadsheets/d/e/2PACX-1vRqP8j4QScNXuwlYML6cxbyE39n3SAhU2QlsvYI6OjfTE-4rhnTMeFgx4p18iK5AScRXn3QmQAO76qg/pub?output=csv&gid=0
        schedule: https://docs.google.com/spreadsheets/d/e/2PACX-1vS3BuJdSO86vuMg_izNVNdUH0YrnpiE_yMr-pt_ckTIuidyNTJmXDSd4fWceS6OKyDOzNtbO9B71lS7/pub?output=csv&gid=0
      Segunda:
        order: 2
        gcalendar_color: 9
        players: https://docs.google.com/spreadsheets/d/e/2PACX-1vQZkFhb83WaxFiiu3B4iOBhkEd9Cau8KzLswH1waFn6yI8aForqBqn3a4OKpq7nqrENxgByYvKAp5LE/pub?output=csv&gid=561683622
        results: https://docs.google.com/spreadsheets/d/e/2PACX-1vRqP8j4QScNXuwlYML6cxbyE39n3SAhU2QlsvYI6OjfTE-4rhnTMeFgx4p18iK5AScRXn3QmQAO76qg/pub?output=csv&gid=1078056963
        schedule: https://docs.google.com/spreadsheets/d/e/2PACX-1vS3BuJdSO86vuMg_izNVNdUH0YrnpiE_yMr-pt_ckTIuidyNTJmXDSd4fWceS6OKyDOzNtbO9B71lS7/pub?output=csv&gid=384769640
      Naranja:
        order: 6
        gcalendar_color: 3
        players: https://docs.google.com/spreadsheets/d/e/2PACX-1vQZkFhb83WaxFiiu3B4iOBhkEd9Cau8KzLswH1waFn6yI8aForqBqn3a4OKpq7nqrENxgByYvKAp5LE/pub?output=csv&gid=481307165
        results: https://docs.google.com/spreadsheets/d/e/2PACX-1vRqP8j4QScNXuwlYML6cxbyE39n3SAhU2QlsvYI6OjfTE-4rhnTMeFgx4p18iK5AScRXn3QmQAO76qg/pub?output=csv&gid=1290077699
        schedule: https://docs.google.com/spreadsheets/d/e/2PACX-1vS3BuJdSO86vuMg_izNVNdUH0YrnpiE_yMr-pt_ckTIuidyNTJmXDSd4fWceS6OKyDOzNtbO9B71lS7/pub?output=csv&gid=828628157
      Rosa:
        order: 4
        gcalendar_color: 4
        players: https://docs.google.com/spreadsheets/d/e/2PACX-1vQZkFhb83WaxFiiu3B4iOBhkEd9Cau8KzLswH1waFn6yI8aForqBqn3a4OKpq7nqrENxgByYvKAp5LE/pub?output=csv&gid=1464030688
        results: https://docs.google.com/spreadsheets/d/e/2PACX-1vRqP8j4QScNXuwlYML6cxbyE39n3SAhU2QlsvYI6OjfTE-4rhnTMeFgx4p18iK5AScRXn3QmQAO76qg/pub?output=csv&gid=413133258
        schedule: https://docs.google.com/spreadsheets/d/e/2PACX-1vS3BuJdSO86vuMg_izNVNdUH0YrnpiE_yMr-pt_ckTIuidyNTJmXDSd4fWceS6OKyDOzNtbO9B71lS7/pub?output=csv&gid=1174688863
